/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Games: () => import('#controllers/games_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profiles: () => import('#controllers/profiles_controller'),
  Session: () => import('#controllers/session_controller'),
}
