/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class MatchSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'p1Choice', 'p2Choice', 'player1Id', 'player2Id', 'roomId', 'roundNumber', 'updatedAt', 'winnerId'] as const
  $columns = MatchSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare p1Choice: string | null
  @column()
  declare p2Choice: string | null
  @column()
  declare player1Id: number | null
  @column()
  declare player2Id: number | null
  @column()
  declare roomId: number | null
  @column()
  declare roundNumber: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare winnerId: number | null
}

export class RoomPlayerSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'roomId', 'score', 'updatedAt', 'userId'] as const
  $columns = RoomPlayerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roomId: number | null
  @column()
  declare score: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class RoomSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'currentRound', 'hostId', 'id', 'status', 'updatedAt'] as const
  $columns = RoomSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentRound: number
  @column()
  declare hostId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
